### ISSUE TITLE
What's this actually about?

### ISSUE THREAD

**Issue by void-sys1** [UEFI-code/DDLC-MonikaInKernel#9]
So i was wondering, what's this actually about? like i know that it will give monika access to kernel but what will that do? will i be able to talk to her?
thanks in advance!

**Comment by UEFI-code** [comment]
Pls check privious issues.

Pls note that kernel access only enable Monika to monitoring and Hook other process in OS, and if you want to talk here you need focus on AI and interface parts.

Currently not finished yet, you can coding yourself or wait I have spare time

iPhoneから送信

2024/06/07 13:58、Null_sys ***@***.***>のメール:

﻿

So i was wondering, what's this actually about? like i know that it will give monika access to kernel but what will that do? will i be able to talk to her?
thanks in advance!

**Comment by UEFI-code** [comment]
https://github.com/UEFI-code/DDLC-MonikaInKernel/releases/tag/v0.0.1
